#! /bin/python3
import argparse
from app import Application


def parse_cmdline():
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--json-file', default='images.json',
                        help="JSON image file to load")
    return parser.parse_args()


def main(options):
    Application(options.json_file).run()


if __name__ == '__main__':
    main(parse_cmdline())
